Write image update date earlier
ubports/system-settings pull request #159
Opened 2019-05-27 20:42 UTC by Flohack74

This will fix ubports/ubuntu-touch#1139

2019-05-28 00:41 UTC, dobey commented
Any chance to add a regression test for this, which fails without the change, and passes with?

2019-05-28 08:52 UTC, Flohack74 commented
Sure I can do this, my first time to do a test for ubuntu touch :)

2019-05-28 08:53 UTC, Flohack74 commented
By the way I am testing it today on my N5 to see if it really works, had to wait for the nightly devel.

2019-05-30 01:21 UTC, dobey requested changes

2019-05-30 01:21 UTC, dobey commented on tests/plugins/system-update/tst_updatemodel.cpp
> +        QVERIFY(passed);
Can you please revert these superfluous logging changes to the tests, so that it just does the QCOMPARE() again?

2019-05-31 13:02 UTC, dobey approved these changes

2019-05-31 13:02 UTC, merged