Add ReinstallAllApps and FirmwareUpdate pages/apis
ubports/system-settings pull request #71
Opened 2018-08-10 12:44 UTC by mariogrip

This adds  ReinstallAllApps and FirmwareUpdate pages/apis

2018-08-10 13:06 UTC, NeoTheThird requested changes
Else than my comments, code looks OK. Seems to work as well. Do we have firmware upgrades prepared for all devices that need them?

2018-08-10 13:06 UTC, NeoTheThird commented on plugins/system-update/FirmwareUpdate.qml
> + * Copyright (C) 2018 Marius Gripsgard <marius@ubports.com>
Shouldn't this be UBports Community?

2018-08-10 13:06 UTC, NeoTheThird commented on plugins/system-update/FirmwareUpdate.qml
> +              root.partitions = ""
please make semicolons consistent in the JS parts

2018-08-10 13:06 UTC, NeoTheThird commented on plugins/system-update/FirmwareUpdate.qml
> +                  text: i18n.tr("The device will automatically restart after installing is done.")
Not sure this grammar is correct. Shouldn't it be "The device will restart automatically after installing is done."?

2018-08-10 13:10 UTC, mariogrip commented on plugins/system-update/FirmwareUpdate.qml
> + * Copyright (C) 2018 Marius Gripsgard <marius@ubports.com>
Yeah, will change that, i have used The UBports project elsewhere

2018-08-10 13:12 UTC, mariogrip commented on plugins/system-update/FirmwareUpdate.qml
> +              root.partitions = ""
i wish sometimes JS requires it, since i only add semicolon when my brain does it automatically so :P most of the times i forget, but will fix it

2018-08-10 13:12 UTC, mariogrip commented on plugins/system-update/FirmwareUpdate.qml
> +                  text: i18n.tr("The device will automatically restart after installing is done.")
Yeah

2018-08-10 13:17 UTC, mariogrip commented
Review comment fixed

2018-08-11 11:01 UTC, NeoTheThird requested changes

2018-08-11 11:01 UTC, NeoTheThird commented on plugins/system-update/ReinstallAllApps.qml
> + * Copyright (C) 2018 Marius Gripsgard <marius@ubports.com>
Copyright here

2018-08-11 11:02 UTC, NeoTheThird commented on plugins/system-update/FirmwareUpdate.qml
> +              root.partitions = ""
yeah...

2018-08-13 15:49 UTC, NeoTheThird approved these changes

2018-08-13 17:03 UTC, merged