Rejigger ClickAppNotifications page
ubports/system-settings pull request #85
Opened 2018-10-01 21:07 UTC by UniversalSuperBox

Turns out there's a switch in ClickAppNotifications.qml which enables
or disables all notification types for the app. It gets automatically
switched when the user disables all notification types. Problem is, it
doesn't show up... it's behind the header!

This commit changes the page around so that the switch shows correctly.
It also makes the page scrollable and fixes a couple of papercuts I saw
from playing around with it. Now when the switch becomes disabled,
all of the notification-specific checkboxes don't display. When the
switch is enabled again, the checkboxes come back. Ahh, satisfying.

Closes ubports/ubuntu-touch#831

2018-10-01 21:38 UTC, mardy requested changes
A few inline comments :-)

2018-10-01 21:38 UTC, mardy commented on plugins/notifications/ClickAppNotifications.qml
> +        title: entry ? entry.displayName : ""
don't you need to add

    flickable: clickAppNotificationsFlickable

here?

2018-10-01 21:38 UTC, mardy commented on plugins/notifications/ClickAppNotifications.qml
> +Page {
Is this change really needed, if you add the Flickable?

2018-10-01 21:38 UTC, mardy commented on plugins/notifications/ClickAppNotifications.qml
> +
remove this

2018-10-01 21:38 UTC, mardy commented on plugins/notifications/ClickAppNotifications.qml
> +
and this :-)

2018-10-01 21:38 UTC, mardy commented on plugins/notifications/ClickAppNotifications.qml
> +        flickableDirection: Flickable.VerticalFlick
you need to set `contentHeight`, too

2018-10-01 21:38 UTC, mardy commented on plugins/notifications/ClickAppNotifications.qml
> +            top: pageHeader.bottom
This should not be needed, the `Page` element will handle it itself. Just use `anchors.fill: parent`.

2018-10-01 21:41 UTC, mardy commented
See here for an example on how to use Page + Flickable + Column: https://gitlab.com/mardy/imaginario/blob/master/src/ubuntu-touch/qml/SettingsPage.qml

2018-10-01 22:10 UTC, UniversalSuperBox commented
Using Page+Flickable+Column is *okay*, but it's very rare that this page goes past the bottom border of the screen. So, when you scroll down the header goes away. It doesn't make much sense for this page.

2018-10-02 06:04 UTC, mardy commented
Please elaborate a bit more :-) If it's rare for this page to go past the bottom of the screen, it means that it's also rare for this page to be scrolled and for the header to disappear, so I don't see a problem here.

2018-10-02 13:32 UTC, UniversalSuperBox commented
It was my own misunderstanding of how to use these elements properly that caused the issue. I've addressed the requested changes and the page seems to work equally as well.

2018-10-02 14:42 UTC, mardy requested changes
Just a minor stylistic issue now :-)

2018-10-02 14:42 UTC, mardy commented on plugins/notifications/ClickAppNotifications.qml
> -
keep this line, it's a good practice to separe the public properties from the internal ones

2018-10-02 14:46 UTC, UniversalSuperBox commented
There, that should fix that. I didn't know that style before, thanks!

2018-10-02 15:04 UTC, mardy approved these changes

2018-10-02 15:04 UTC, merged